title: Anthony Pinzone | Cardiovascular Physiology and Signal Processing | Performance Science
description:   Modeling performance, behavior, and physiological systems
theme: jekyll-theme-slate
markdown: kramdown
